# Generated by Django 2.0.7 on 2020-06-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(choices=[('AM', 'America/Los_Angeles'), ('AS', 'Asia/Kolkata')], default='AM', max_length=2)),
                ('real_name', models.CharField(max_length=20)),
                ('activity', models.ManyToManyField(blank=True, to='user_activities.ActivityPeriods')),
            ],
        ),
    ]
