# Generated by Django 2.0.7 on 2020-06-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiods',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_activities.Users'),
        ),
    ]
