# Generated by Django 2.0.7 on 2020-06-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0003_remove_users_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='real_name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
    ]
