# Generated by Django 2.0.7 on 2020-06-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_activityperiods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiods',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activityperiods',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
