# Generated by Django 2.0.7 on 2020-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('products', '0004_products_activity'),
    # ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(choices=[('AM', 'America/Los_Angeles'), ('AS', 'Asia/Kolkata')], default='AM', max_length=2)),
                ('real_name', models.CharField(max_length=20)),
                ('activity', models.ManyToManyField(to='products.ActivityPeriods')),
            ],
        ),
    ]
