# Generated by Django 2.0.7 on 2020-06-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('products', '0006_auto_20200624_1614'),
    # ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activity',
            field=models.ManyToManyField(blank=True, to='products.ActivityPeriods'),
        ),
    ]
