# Generated by Django 2.0.7 on 2020-06-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200624_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activity',
            field=models.ManyToManyField(blank=True, related_name='activity_rec', related_query_name='activity', to='products.ActivityPeriods'),
        ),
    ]
